package repository

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/google/uuid"
	"github.com/meridien-engine/meridien-engine/internal/domain"
)

// KnowledgeRepository implements domain.KnowledgeRepository using pgvector.
// All vector operations use raw SQL (pgvector is not supported by sqlc).
type KnowledgeRepository struct {
	db *sql.DB
}

func NewKnowledgeRepository(database *sql.DB) *KnowledgeRepository {
	return &KnowledgeRepository{db: database}
}

// Query performs a cosine similarity search against knowledge_nodes for the
// active tenant. Returns the top-k most relevant chunks.
//
// The query uses the <=> operator (pgvector cosine distance).
// Distance is converted to similarity score: score = 1 - distance.
func (r *KnowledgeRepository) Query(
	ctx context.Context,
	queryEmbedding []float32,
	topK int,
) ([]domain.KnowledgeChunk, error) {
	businessID, err := BusinessIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Convert []float32 to Postgres vector literal: '[0.1,0.2,...]'
	vecLiteral := float32SliceToVector(queryEmbedding)

	// RLS is enforced by the active session variable.
	// We still pass business_id explicitly as a belt-and-suspenders check.
	rows, err := r.db.QueryContext(ctx, `
		SELECT
			id,
			source_name,
			content,
			1 - (embedding <=> $1::vector) AS score
		FROM knowledge_nodes
		WHERE business_id = $2::uuid
		ORDER BY embedding <=> $1::vector
		LIMIT $3
	`, vecLiteral, businessID, topK)
	if err != nil {
		return nil, fmt.Errorf("knowledge vector query: %w", err)
	}
	defer rows.Close()

	var chunks []domain.KnowledgeChunk
	for rows.Next() {
		var c domain.KnowledgeChunk
		var nodeID uuid.UUID
		if err := rows.Scan(&nodeID, &c.Source, &c.Content, &c.Score); err != nil {
			return nil, fmt.Errorf("scan knowledge chunk: %w", err)
		}
		c.NodeID = nodeID
		chunks = append(chunks, c)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("knowledge rows iteration: %w", err)
	}

	return chunks, nil
}

// InsertChunk stores a single pre-embedded knowledge chunk for the active tenant.
// Embeddings should be generated by the caller (Knowledge service) before this call.
func (r *KnowledgeRepository) InsertChunk(
	ctx context.Context,
	source, content string,
	embedding []float32,
) error {
	businessID, err := BusinessIDFromContext(ctx)
	if err != nil {
		return err
	}

	vecLiteral := float32SliceToVector(embedding)

	err = ExecWithTenant(ctx, r.db, businessID, func(tx *sql.Tx) error {
		_, err := tx.ExecContext(ctx, `
			INSERT INTO knowledge_nodes (business_id, source_name, content, embedding)
			VALUES ($1::uuid, $2, $3, $4::vector)
		`, businessID, source, content, vecLiteral)
		return err
	})
	if err != nil {
		return fmt.Errorf("insert knowledge chunk: %w", err)
	}
	return nil
}

// ─── helpers ─────────────────────────────────────────────────────────────────

// float32SliceToVector converts a Go float32 slice to Postgres vector literal.
// e.g. [0.1, 0.2, 0.3] → "[0.1,0.2,0.3]"
func float32SliceToVector(v []float32) string {
	if len(v) == 0 {
		return "[]"
	}
	b := make([]byte, 0, len(v)*8)
	b = append(b, '[')
	for i, f := range v {
		if i > 0 {
			b = append(b, ',')
		}
		b = fmt.Appendf(b, "%g", f)
	}
	b = append(b, ']')
	return string(b)
}
