// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getDashboardOverviewMetrics = `-- name: GetDashboardOverviewMetrics :one
SELECT 
    COALESCE(SUM(CASE WHEN o.status = 'completed' THEN o.total_price ELSE 0 END), 0)::numeric AS total_revenue,
    COUNT(o.id)::bigint AS orders_processed,
    COALESCE(
        COUNT(CASE WHEN o.source NOT IN ('portal', 'web') THEN 1 END)::numeric / 
        NULLIF(COUNT(o.id), 0)::numeric * 100, 
        0
    )::numeric AS interception_rate,
    (
        SELECT COUNT(t.id) 
        FROM interaction_traces t
        JOIN interaction_logs l ON t.interaction_log_id = l.id
        WHERE l.business_id = $1 AND t.hitl_status = 'pending'
    )::bigint AS pending_review
FROM orders o
WHERE o.business_id = $1
`

type GetDashboardOverviewMetricsRow struct {
	TotalRevenue     decimal.Decimal `json:"total_revenue"`
	OrdersProcessed  int64           `json:"orders_processed"`
	InterceptionRate decimal.Decimal `json:"interception_rate"`
	PendingReview    int64           `json:"pending_review"`
}

func (q *Queries) GetDashboardOverviewMetrics(ctx context.Context, businessID uuid.UUID) (GetDashboardOverviewMetricsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardOverviewMetrics, businessID)
	var i GetDashboardOverviewMetricsRow
	err := row.Scan(
		&i.TotalRevenue,
		&i.OrdersProcessed,
		&i.InterceptionRate,
		&i.PendingReview,
	)
	return i, err
}

const getRevenueLast7Days = `-- name: GetRevenueLast7Days :many
WITH date_series AS (
    SELECT generate_series(
        current_date - interval '6 days',
        current_date,
        '1 day'::interval
    )::date AS day
)
SELECT 
    ds.day::date AS date,
    COALESCE(SUM(o.total_price), 0)::numeric AS total_revenue
FROM date_series ds
LEFT JOIN orders o ON ds.day = (o.created_at AT TIME ZONE 'UTC')::date
    AND o.business_id = $1
    AND o.status = 'completed'
GROUP BY ds.day
ORDER BY ds.day
`

type GetRevenueLast7DaysRow struct {
	Date         time.Time       `json:"date"`
	TotalRevenue decimal.Decimal `json:"total_revenue"`
}

func (q *Queries) GetRevenueLast7Days(ctx context.Context, businessID uuid.UUID) ([]GetRevenueLast7DaysRow, error) {
	rows, err := q.db.QueryContext(ctx, getRevenueLast7Days, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRevenueLast7DaysRow{}
	for rows.Next() {
		var i GetRevenueLast7DaysRow
		if err := rows.Scan(&i.Date, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
