// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: businesses.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBusiness = `-- name: CreateBusiness :one

INSERT INTO businesses (
  name,
  slug,
  owner_id,
  category_id,
  contact_phone,
  contact_email
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, name, slug, owner_id, category_id, contact_phone, contact_email, logo_url, plan, status, created_at, updated_at, deleted_at
`

type CreateBusinessParams struct {
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	OwnerID      uuid.UUID      `json:"owner_id"`
	CategoryID   uuid.NullUUID  `json:"category_id"`
	ContactPhone sql.NullString `json:"contact_phone"`
	ContactEmail sql.NullString `json:"contact_email"`
}

// queries/businesses.sql
func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, createBusiness,
		arg.Name,
		arg.Slug,
		arg.OwnerID,
		arg.CategoryID,
		arg.ContactPhone,
		arg.ContactEmail,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CategoryID,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.LogoUrl,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBusinessByID = `-- name: GetBusinessByID :one
SELECT id, name, slug, owner_id, category_id, contact_phone, contact_email, logo_url, plan, status, created_at, updated_at, deleted_at FROM businesses
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetBusinessByID(ctx context.Context, id uuid.UUID) (Business, error) {
	row := q.db.QueryRowContext(ctx, getBusinessByID, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CategoryID,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.LogoUrl,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBusinessBySlug = `-- name: GetBusinessBySlug :one
SELECT id, name, slug, owner_id, category_id, contact_phone, contact_email, logo_url, plan, status, created_at, updated_at, deleted_at FROM businesses
WHERE slug = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetBusinessBySlug(ctx context.Context, slug string) (Business, error) {
	row := q.db.QueryRowContext(ctx, getBusinessBySlug, slug)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CategoryID,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.LogoUrl,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBusinessCategories = `-- name: ListBusinessCategories :many
SELECT id, name, name_ar, slug FROM business_categories
ORDER BY name ASC
`

func (q *Queries) ListBusinessCategories(ctx context.Context) ([]BusinessCategory, error) {
	rows, err := q.db.QueryContext(ctx, listBusinessCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessCategory{}
	for rows.Next() {
		var i BusinessCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameAr,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBusiness = `-- name: UpdateBusiness :one
UPDATE businesses
SET
  name          = COALESCE($2, name),
  contact_phone = COALESCE($3, contact_phone),
  contact_email = COALESCE($4, contact_email),
  logo_url      = COALESCE($5, logo_url),
  status        = COALESCE($6, status)
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, slug, owner_id, category_id, contact_phone, contact_email, logo_url, plan, status, created_at, updated_at, deleted_at
`

type UpdateBusinessParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	ContactPhone sql.NullString `json:"contact_phone"`
	ContactEmail sql.NullString `json:"contact_email"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Status       string         `json:"status"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error) {
	row := q.db.QueryRowContext(ctx, updateBusiness,
		arg.ID,
		arg.Name,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.LogoUrl,
		arg.Status,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerID,
		&i.CategoryID,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.LogoUrl,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
