// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createCustomerProfile = `-- name: CreateCustomerProfile :one
INSERT INTO customer_profiles (
  business_id, unified_name, customer_tier
) VALUES (
  $1, $2, $3
)
RETURNING id, business_id, unified_name, customer_tier, semantic_summary, created_at, updated_at
`

type CreateCustomerProfileParams struct {
	BusinessID   uuid.UUID      `json:"business_id"`
	UnifiedName  sql.NullString `json:"unified_name"`
	CustomerTier string         `json:"customer_tier"`
}

func (q *Queries) CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (CustomerProfile, error) {
	row := q.db.QueryRowContext(ctx, createCustomerProfile, arg.BusinessID, arg.UnifiedName, arg.CustomerTier)
	var i CustomerProfile
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UnifiedName,
		&i.CustomerTier,
		&i.SemanticSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByChannel = `-- name: GetCustomerByChannel :one
SELECT cp.id, cp.business_id, cp.unified_name, cp.customer_tier, cp.semantic_summary, cp.created_at, cp.updated_at
FROM customer_profiles cp
JOIN customer_channels cc ON cc.customer_profile_id = cp.id
WHERE cc.channel_type = $1
  AND cc.channel_external_id = $2
LIMIT 1
`

type GetCustomerByChannelParams struct {
	ChannelType       string `json:"channel_type"`
	ChannelExternalID string `json:"channel_external_id"`
}

// Primary Synapse lookup: find a customer from their external channel ID.
func (q *Queries) GetCustomerByChannel(ctx context.Context, arg GetCustomerByChannelParams) (CustomerProfile, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByChannel, arg.ChannelType, arg.ChannelExternalID)
	var i CustomerProfile
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UnifiedName,
		&i.CustomerTier,
		&i.SemanticSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerProfileByID = `-- name: GetCustomerProfileByID :one
SELECT id, business_id, unified_name, customer_tier, semantic_summary, created_at, updated_at FROM customer_profiles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCustomerProfileByID(ctx context.Context, id uuid.UUID) (CustomerProfile, error) {
	row := q.db.QueryRowContext(ctx, getCustomerProfileByID, id)
	var i CustomerProfile
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UnifiedName,
		&i.CustomerTier,
		&i.SemanticSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT 
    cp.id, 
    cp.unified_name, 
    cp.customer_tier, 
    cp.semantic_summary, 
    cp.created_at,
    (SELECT cc.channel_type 
     FROM customer_channels cc 
     WHERE cc.customer_profile_id = cp.id 
     ORDER BY cc.created_at ASC
     LIMIT 1)::varchar AS primary_channel
FROM customer_profiles cp
WHERE cp.business_id = $3
ORDER BY cp.created_at DESC
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
	BusinessID uuid.UUID `json:"business_id"`
}

type ListCustomersRow struct {
	ID              uuid.UUID      `json:"id"`
	UnifiedName     sql.NullString `json:"unified_name"`
	CustomerTier    string         `json:"customer_tier"`
	SemanticSummary sql.NullString `json:"semantic_summary"`
	CreatedAt       time.Time      `json:"created_at"`
	PrimaryChannel  string         `json:"primary_channel"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers, arg.Limit, arg.Offset, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersRow{}
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.UnifiedName,
			&i.CustomerTier,
			&i.SemanticSummary,
			&i.CreatedAt,
			&i.PrimaryChannel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerTier = `-- name: UpdateCustomerTier :one
UPDATE customer_profiles
SET customer_tier = $2
WHERE id = $1
RETURNING id, business_id, unified_name, customer_tier, semantic_summary, created_at, updated_at
`

type UpdateCustomerTierParams struct {
	ID           uuid.UUID `json:"id"`
	CustomerTier string    `json:"customer_tier"`
}

func (q *Queries) UpdateCustomerTier(ctx context.Context, arg UpdateCustomerTierParams) (CustomerProfile, error) {
	row := q.db.QueryRowContext(ctx, updateCustomerTier, arg.ID, arg.CustomerTier)
	var i CustomerProfile
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UnifiedName,
		&i.CustomerTier,
		&i.SemanticSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSemanticSummary = `-- name: UpdateSemanticSummary :one
UPDATE customer_profiles
SET semantic_summary = $2
WHERE id = $1
RETURNING id, business_id, unified_name, customer_tier, semantic_summary, created_at, updated_at
`

type UpdateSemanticSummaryParams struct {
	ID              uuid.UUID      `json:"id"`
	SemanticSummary sql.NullString `json:"semantic_summary"`
}

func (q *Queries) UpdateSemanticSummary(ctx context.Context, arg UpdateSemanticSummaryParams) (CustomerProfile, error) {
	row := q.db.QueryRowContext(ctx, updateSemanticSummary, arg.ID, arg.SemanticSummary)
	var i CustomerProfile
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UnifiedName,
		&i.CustomerTier,
		&i.SemanticSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCustomerChannel = `-- name: UpsertCustomerChannel :one
INSERT INTO customer_channels (
  customer_profile_id, channel_type, channel_external_id
) VALUES (
  $1, $2, $3
)
ON CONFLICT (customer_profile_id, channel_type, channel_external_id)
DO UPDATE SET customer_profile_id = EXCLUDED.customer_profile_id
RETURNING id, customer_profile_id, channel_type, channel_external_id, created_at
`

type UpsertCustomerChannelParams struct {
	CustomerProfileID uuid.UUID `json:"customer_profile_id"`
	ChannelType       string    `json:"channel_type"`
	ChannelExternalID string    `json:"channel_external_id"`
}

// Resolves or creates the channel mapping, returning the customer profile.
// Used by Synapse on every inbound message to identify the customer.
func (q *Queries) UpsertCustomerChannel(ctx context.Context, arg UpsertCustomerChannelParams) (CustomerChannel, error) {
	row := q.db.QueryRowContext(ctx, upsertCustomerChannel, arg.CustomerProfileID, arg.ChannelType, arg.ChannelExternalID)
	var i CustomerChannel
	err := row.Scan(
		&i.ID,
		&i.CustomerProfileID,
		&i.ChannelType,
		&i.ChannelExternalID,
		&i.CreatedAt,
	)
	return i, err
}
