// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getLiveFeed = `-- name: GetLiveFeed :many
SELECT 
    id,
    'interaction'::text AS item_type,
    channel::text AS title_meta,
    inbound_msg::text AS description,
    created_at
FROM interaction_logs
WHERE interaction_logs.business_id = $1::uuid
UNION ALL
SELECT 
    id,
    'order'::text AS item_type,
    status::text AS title_meta,
    CAST(total_price AS TEXT) AS description,
    created_at
FROM orders
WHERE orders.business_id = $1::uuid
ORDER BY created_at DESC
LIMIT 15
`

type GetLiveFeedRow struct {
	ID          uuid.UUID `json:"id"`
	ItemType    string    `json:"item_type"`
	TitleMeta   string    `json:"title_meta"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetLiveFeed(ctx context.Context, businessID uuid.UUID) ([]GetLiveFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, getLiveFeed, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLiveFeedRow{}
	for rows.Next() {
		var i GetLiveFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemType,
			&i.TitleMeta,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
