// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hitl.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const listHITLTraces = `-- name: ListHITLTraces :many
SELECT 
  it.id AS trace_id,
  it.interaction_log_id,
  it.retrieved_contexts,
  it.system_prompt,
  it.raw_agent_thoughts,
  it.tools_called,
  it.workflow_id,
  it.hitl_status,
  it.suspended_at,
  it.expires_at,
  it.created_at AS trace_created_at,
  il.id AS log_id,
  il.business_id,
  il.customer_id,
  il.channel,
  il.inbound_msg,
  il.outbound_msg,
  il.tokens_used,
  il.latency_ms,
  il.created_at AS log_created_at
FROM interaction_traces it
JOIN interaction_logs il ON it.interaction_log_id = il.id
WHERE il.business_id = $1
  AND it.hitl_status != 'none'
ORDER BY it.suspended_at DESC NULLS LAST, il.created_at DESC
LIMIT $3 OFFSET $2
`

type ListHITLTracesParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Off        int32     `json:"off"`
	Lim        int32     `json:"lim"`
}

type ListHITLTracesRow struct {
	TraceID           uuid.UUID       `json:"trace_id"`
	InteractionLogID  uuid.UUID       `json:"interaction_log_id"`
	RetrievedContexts json.RawMessage `json:"retrieved_contexts"`
	SystemPrompt      string          `json:"system_prompt"`
	RawAgentThoughts  string          `json:"raw_agent_thoughts"`
	ToolsCalled       json.RawMessage `json:"tools_called"`
	WorkflowID        sql.NullString  `json:"workflow_id"`
	HitlStatus        string          `json:"hitl_status"`
	SuspendedAt       sql.NullTime    `json:"suspended_at"`
	ExpiresAt         sql.NullTime    `json:"expires_at"`
	TraceCreatedAt    time.Time       `json:"trace_created_at"`
	LogID             uuid.UUID       `json:"log_id"`
	BusinessID        uuid.UUID       `json:"business_id"`
	CustomerID        uuid.UUID       `json:"customer_id"`
	Channel           string          `json:"channel"`
	InboundMsg        string          `json:"inbound_msg"`
	OutboundMsg       string          `json:"outbound_msg"`
	TokensUsed        int32           `json:"tokens_used"`
	LatencyMs         int32           `json:"latency_ms"`
	LogCreatedAt      time.Time       `json:"log_created_at"`
}

func (q *Queries) ListHITLTraces(ctx context.Context, arg ListHITLTracesParams) ([]ListHITLTracesRow, error) {
	rows, err := q.db.QueryContext(ctx, listHITLTraces, arg.BusinessID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHITLTracesRow{}
	for rows.Next() {
		var i ListHITLTracesRow
		if err := rows.Scan(
			&i.TraceID,
			&i.InteractionLogID,
			&i.RetrievedContexts,
			&i.SystemPrompt,
			&i.RawAgentThoughts,
			&i.ToolsCalled,
			&i.WorkflowID,
			&i.HitlStatus,
			&i.SuspendedAt,
			&i.ExpiresAt,
			&i.TraceCreatedAt,
			&i.LogID,
			&i.BusinessID,
			&i.CustomerID,
			&i.Channel,
			&i.InboundMsg,
			&i.OutboundMsg,
			&i.TokensUsed,
			&i.LatencyMs,
			&i.LogCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHITLStatus = `-- name: UpdateHITLStatus :exec
UPDATE interaction_traces
SET 
  hitl_status = $1
WHERE interaction_traces.id = $2
  AND interaction_traces.interaction_log_id IN (
    SELECT interaction_logs.id FROM interaction_logs WHERE interaction_logs.business_id = $3
  )
`

type UpdateHITLStatusParams struct {
	HitlStatus string    `json:"hitl_status"`
	TraceID    uuid.UUID `json:"trace_id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) UpdateHITLStatus(ctx context.Context, arg UpdateHITLStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateHITLStatus, arg.HitlStatus, arg.TraceID, arg.BusinessID)
	return err
}
