// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interactions.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createInteractionLog = `-- name: CreateInteractionLog :one
INSERT INTO interaction_logs (
  business_id, customer_id, channel, inbound_msg, outbound_msg, tokens_used, latency_ms
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, business_id, customer_id, channel, inbound_msg, outbound_msg, tokens_used, latency_ms, created_at
`

type CreateInteractionLogParams struct {
	BusinessID  uuid.UUID `json:"business_id"`
	CustomerID  uuid.UUID `json:"customer_id"`
	Channel     string    `json:"channel"`
	InboundMsg  string    `json:"inbound_msg"`
	OutboundMsg string    `json:"outbound_msg"`
	TokensUsed  int32     `json:"tokens_used"`
	LatencyMs   int32     `json:"latency_ms"`
}

func (q *Queries) CreateInteractionLog(ctx context.Context, arg CreateInteractionLogParams) (InteractionLog, error) {
	row := q.db.QueryRowContext(ctx, createInteractionLog,
		arg.BusinessID,
		arg.CustomerID,
		arg.Channel,
		arg.InboundMsg,
		arg.OutboundMsg,
		arg.TokensUsed,
		arg.LatencyMs,
	)
	var i InteractionLog
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.Channel,
		&i.InboundMsg,
		&i.OutboundMsg,
		&i.TokensUsed,
		&i.LatencyMs,
		&i.CreatedAt,
	)
	return i, err
}

const createInteractionTrace = `-- name: CreateInteractionTrace :one
INSERT INTO interaction_traces (
  interaction_log_id, retrieved_contexts, system_prompt, raw_agent_thoughts, tools_called
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, interaction_log_id, retrieved_contexts, system_prompt, raw_agent_thoughts, tools_called, created_at
`

type CreateInteractionTraceParams struct {
	InteractionLogID  uuid.UUID       `json:"interaction_log_id"`
	RetrievedContexts json.RawMessage `json:"retrieved_contexts"`
	SystemPrompt      string          `json:"system_prompt"`
	RawAgentThoughts  string          `json:"raw_agent_thoughts"`
	ToolsCalled       json.RawMessage `json:"tools_called"`
}

func (q *Queries) CreateInteractionTrace(ctx context.Context, arg CreateInteractionTraceParams) (InteractionTrace, error) {
	row := q.db.QueryRowContext(ctx, createInteractionTrace,
		arg.InteractionLogID,
		arg.RetrievedContexts,
		arg.SystemPrompt,
		arg.RawAgentThoughts,
		arg.ToolsCalled,
	)
	var i InteractionTrace
	err := row.Scan(
		&i.ID,
		&i.InteractionLogID,
		&i.RetrievedContexts,
		&i.SystemPrompt,
		&i.RawAgentThoughts,
		&i.ToolsCalled,
		&i.CreatedAt,
	)
	return i, err
}

const getInteractionWithTrace = `-- name: GetInteractionWithTrace :one
SELECT
  il.id,
  il.business_id,
  il.customer_id,
  il.channel,
  il.inbound_msg,
  il.outbound_msg,
  il.tokens_used,
  il.latency_ms,
  il.created_at,
  it.retrieved_contexts,
  it.system_prompt,
  it.raw_agent_thoughts,
  it.tools_called
FROM interaction_logs il
LEFT JOIN interaction_traces it ON it.interaction_log_id = il.id
WHERE il.id = $1
`

type GetInteractionWithTraceRow struct {
	ID                uuid.UUID             `json:"id"`
	BusinessID        uuid.UUID             `json:"business_id"`
	CustomerID        uuid.UUID             `json:"customer_id"`
	Channel           string                `json:"channel"`
	InboundMsg        string                `json:"inbound_msg"`
	OutboundMsg       string                `json:"outbound_msg"`
	TokensUsed        int32                 `json:"tokens_used"`
	LatencyMs         int32                 `json:"latency_ms"`
	CreatedAt         time.Time             `json:"created_at"`
	RetrievedContexts pqtype.NullRawMessage `json:"retrieved_contexts"`
	SystemPrompt      sql.NullString        `json:"system_prompt"`
	RawAgentThoughts  sql.NullString        `json:"raw_agent_thoughts"`
	ToolsCalled       pqtype.NullRawMessage `json:"tools_called"`
}

// Fetches a single interaction log and its associated trace for Compass.
func (q *Queries) GetInteractionWithTrace(ctx context.Context, id uuid.UUID) (GetInteractionWithTraceRow, error) {
	row := q.db.QueryRowContext(ctx, getInteractionWithTrace, id)
	var i GetInteractionWithTraceRow
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.Channel,
		&i.InboundMsg,
		&i.OutboundMsg,
		&i.TokensUsed,
		&i.LatencyMs,
		&i.CreatedAt,
		&i.RetrievedContexts,
		&i.SystemPrompt,
		&i.RawAgentThoughts,
		&i.ToolsCalled,
	)
	return i, err
}

const listInteractionLogs = `-- name: ListInteractionLogs :many
SELECT id, business_id, customer_id, channel, inbound_msg, outbound_msg, tokens_used, latency_ms, created_at FROM interaction_logs
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListInteractionLogsParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

// Paginated list for Compass dashboard.
func (q *Queries) ListInteractionLogs(ctx context.Context, arg ListInteractionLogsParams) ([]InteractionLog, error) {
	rows, err := q.db.QueryContext(ctx, listInteractionLogs, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InteractionLog{}
	for rows.Next() {
		var i InteractionLog
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.CustomerID,
			&i.Channel,
			&i.InboundMsg,
			&i.OutboundMsg,
			&i.TokensUsed,
			&i.LatencyMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInteractionLogsByCustomer = `-- name: ListInteractionLogsByCustomer :many
SELECT id, business_id, customer_id, channel, inbound_msg, outbound_msg, tokens_used, latency_ms, created_at FROM interaction_logs
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInteractionLogsByCustomer(ctx context.Context, customerID uuid.UUID) ([]InteractionLog, error) {
	rows, err := q.db.QueryContext(ctx, listInteractionLogsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InteractionLog{}
	for rows.Next() {
		var i InteractionLog
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.CustomerID,
			&i.Channel,
			&i.InboundMsg,
			&i.OutboundMsg,
			&i.TokensUsed,
			&i.LatencyMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
