// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertKnowledgeNode = `-- name: InsertKnowledgeNode :one
INSERT INTO knowledge_nodes (
  business_id,
  source_name,
  content,
  embedding
) VALUES (
  $1, $2, $3, $4::vector
)
RETURNING id
`

type InsertKnowledgeNodeParams struct {
	BusinessID uuid.UUID   `json:"business_id"`
	SourceName string      `json:"source_name"`
	Content    string      `json:"content"`
	Column4    interface{} `json:"column_4"`
}

func (q *Queries) InsertKnowledgeNode(ctx context.Context, arg InsertKnowledgeNodeParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertKnowledgeNode,
		arg.BusinessID,
		arg.SourceName,
		arg.Content,
		arg.Column4,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listKnowledgeNodes = `-- name: ListKnowledgeNodes :many
SELECT
  id,
  source_name,
  substring(content from 1 for 200)::text as content_preview,
  created_at
FROM knowledge_nodes
WHERE business_id = $1
ORDER BY created_at DESC
`

type ListKnowledgeNodesRow struct {
	ID             uuid.UUID `json:"id"`
	SourceName     string    `json:"source_name"`
	ContentPreview string    `json:"content_preview"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) ListKnowledgeNodes(ctx context.Context, businessID uuid.UUID) ([]ListKnowledgeNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listKnowledgeNodes, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKnowledgeNodesRow{}
	for rows.Next() {
		var i ListKnowledgeNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceName,
			&i.ContentPreview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
