// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations
SET status = 'accepted'
WHERE token = $1
RETURNING id, business_id, email, role, token, invited_by, status, expires_at, created_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, acceptInvitation, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (
  business_id,
  email,
  role,
  token,
  invited_by,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, business_id, email, role, token, invited_by, status, expires_at, created_at
`

type CreateInvitationParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Email      string    `json:"email"`
	Role       string    `json:"role"`
	Token      string    `json:"token"`
	InvitedBy  uuid.UUID `json:"invited_by"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.BusinessID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createJoinRequest = `-- name: CreateJoinRequest :one
INSERT INTO join_requests (
  user_id,
  business_id,
  message,
  role
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, business_id, message, role, status, reviewed_by, reviewed_at, created_at
`

type CreateJoinRequestParams struct {
	UserID     uuid.UUID      `json:"user_id"`
	BusinessID uuid.UUID      `json:"business_id"`
	Message    sql.NullString `json:"message"`
	Role       string         `json:"role"`
}

func (q *Queries) CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (JoinRequest, error) {
	row := q.db.QueryRowContext(ctx, createJoinRequest,
		arg.UserID,
		arg.BusinessID,
		arg.Message,
		arg.Role,
	)
	var i JoinRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Message,
		&i.Role,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :one

INSERT INTO user_business_memberships (
  user_id,
  business_id,
  role,
  invited_by
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, business_id, role, status, invited_by, created_at, updated_at
`

type CreateMembershipParams struct {
	UserID     uuid.UUID     `json:"user_id"`
	BusinessID uuid.UUID     `json:"business_id"`
	Role       string        `json:"role"`
	InvitedBy  uuid.NullUUID `json:"invited_by"`
}

// queries/memberships.sql
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (UserBusinessMembership, error) {
	row := q.db.QueryRowContext(ctx, createMembership,
		arg.UserID,
		arg.BusinessID,
		arg.Role,
		arg.InvitedBy,
	)
	var i UserBusinessMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireInvitation = `-- name: ExpireInvitation :exec
UPDATE invitations
SET status = 'expired'
WHERE id = $1
`

func (q *Queries) ExpireInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, expireInvitation, id)
	return err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, business_id, email, role, token, invited_by, status, expires_at, created_at FROM invitations
WHERE token  = $1
  AND status = 'pending'
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, business_id, role, status, invited_by, created_at, updated_at FROM user_business_memberships
WHERE user_id    = $1
  AND business_id = $2
  AND status     = 'active'
LIMIT 1
`

type GetMembershipParams struct {
	UserID     uuid.UUID `json:"user_id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (UserBusinessMembership, error) {
	row := q.db.QueryRowContext(ctx, getMembership, arg.UserID, arg.BusinessID)
	var i UserBusinessMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingJoinRequest = `-- name: GetPendingJoinRequest :one
SELECT id, user_id, business_id, message, role, status, reviewed_by, reviewed_at, created_at FROM join_requests
WHERE user_id    = $1
  AND business_id = $2
  AND status     = 'pending'
LIMIT 1
`

type GetPendingJoinRequestParams struct {
	UserID     uuid.UUID `json:"user_id"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) GetPendingJoinRequest(ctx context.Context, arg GetPendingJoinRequestParams) (JoinRequest, error) {
	row := q.db.QueryRowContext(ctx, getPendingJoinRequest, arg.UserID, arg.BusinessID)
	var i JoinRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Message,
		&i.Role,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listBusinessMembers = `-- name: ListBusinessMembers :many
SELECT
  u.id,
  u.email,
  u.first_name,
  u.last_name,
  m.role,
  m.status,
  m.created_at AS joined_at
FROM user_business_memberships m
JOIN users u ON u.id = m.user_id
WHERE m.business_id = $1
  AND u.deleted_at   IS NULL
ORDER BY m.created_at ASC
`

type ListBusinessMembersRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	JoinedAt  time.Time `json:"joined_at"`
}

func (q *Queries) ListBusinessMembers(ctx context.Context, businessID uuid.UUID) ([]ListBusinessMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listBusinessMembers, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusinessMembersRow{}
	for rows.Next() {
		var i ListBusinessMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJoinRequests = `-- name: ListPendingJoinRequests :many
SELECT
  jr.id, jr.user_id, jr.business_id, jr.message, jr.role, jr.status, jr.reviewed_by, jr.reviewed_at, jr.created_at,
  u.email,
  u.first_name,
  u.last_name
FROM join_requests jr
JOIN users u ON u.id = jr.user_id
WHERE jr.business_id = $1
  AND jr.status      = 'pending'
ORDER BY jr.created_at ASC
`

type ListPendingJoinRequestsRow struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	BusinessID uuid.UUID      `json:"business_id"`
	Message    sql.NullString `json:"message"`
	Role       string         `json:"role"`
	Status     string         `json:"status"`
	ReviewedBy uuid.NullUUID  `json:"reviewed_by"`
	ReviewedAt sql.NullTime   `json:"reviewed_at"`
	CreatedAt  time.Time      `json:"created_at"`
	Email      string         `json:"email"`
	FirstName  string         `json:"first_name"`
	LastName   string         `json:"last_name"`
}

func (q *Queries) ListPendingJoinRequests(ctx context.Context, businessID uuid.UUID) ([]ListPendingJoinRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingJoinRequests, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingJoinRequestsRow{}
	for rows.Next() {
		var i ListPendingJoinRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BusinessID,
			&i.Message,
			&i.Role,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBusinesses = `-- name: ListUserBusinesses :many
SELECT
  b.id, b.name, b.slug, b.owner_id, b.category_id, b.contact_phone, b.contact_email, b.logo_url, b.plan, b.status, b.created_at, b.updated_at, b.deleted_at,
  m.role,
  m.status AS membership_status
FROM user_business_memberships m
JOIN businesses b ON b.id = m.business_id
WHERE m.user_id = $1
  AND m.status  = 'active'
  AND b.deleted_at IS NULL
ORDER BY b.name ASC
`

type ListUserBusinessesRow struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	OwnerID          uuid.UUID      `json:"owner_id"`
	CategoryID       uuid.NullUUID  `json:"category_id"`
	ContactPhone     sql.NullString `json:"contact_phone"`
	ContactEmail     sql.NullString `json:"contact_email"`
	LogoUrl          sql.NullString `json:"logo_url"`
	Plan             string         `json:"plan"`
	Status           string         `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	Role             string         `json:"role"`
	MembershipStatus string         `json:"membership_status"`
}

func (q *Queries) ListUserBusinesses(ctx context.Context, userID uuid.UUID) ([]ListUserBusinessesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserBusinesses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserBusinessesRow{}
	for rows.Next() {
		var i ListUserBusinessesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.OwnerID,
			&i.CategoryID,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.LogoUrl,
			&i.Plan,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
			&i.MembershipStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewJoinRequest = `-- name: ReviewJoinRequest :one
UPDATE join_requests
SET
  status      = $2,
  reviewed_by = $3,
  reviewed_at = NOW()
WHERE id = $1
RETURNING id, user_id, business_id, message, role, status, reviewed_by, reviewed_at, created_at
`

type ReviewJoinRequestParams struct {
	ID         uuid.UUID     `json:"id"`
	Status     string        `json:"status"`
	ReviewedBy uuid.NullUUID `json:"reviewed_by"`
}

func (q *Queries) ReviewJoinRequest(ctx context.Context, arg ReviewJoinRequestParams) (JoinRequest, error) {
	row := q.db.QueryRowContext(ctx, reviewJoinRequest, arg.ID, arg.Status, arg.ReviewedBy)
	var i JoinRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Message,
		&i.Role,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE user_business_memberships
SET role = $3
WHERE user_id    = $1
  AND business_id = $2
RETURNING id, user_id, business_id, role, status, invited_by, created_at, updated_at
`

type UpdateMembershipRoleParams struct {
	UserID     uuid.UUID `json:"user_id"`
	BusinessID uuid.UUID `json:"business_id"`
	Role       string    `json:"role"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (UserBusinessMembership, error) {
	row := q.db.QueryRowContext(ctx, updateMembershipRole, arg.UserID, arg.BusinessID, arg.Role)
	var i UserBusinessMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :one
UPDATE user_business_memberships
SET status = $3
WHERE user_id    = $1
  AND business_id = $2
RETURNING id, user_id, business_id, role, status, invited_by, created_at, updated_at
`

type UpdateMembershipStatusParams struct {
	UserID     uuid.UUID `json:"user_id"`
	BusinessID uuid.UUID `json:"business_id"`
	Status     string    `json:"status"`
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (UserBusinessMembership, error) {
	row := q.db.QueryRowContext(ctx, updateMembershipStatus, arg.UserID, arg.BusinessID, arg.Status)
	var i UserBusinessMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
