// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID         uuid.UUID             `json:"id"`
	BusinessID uuid.UUID             `json:"business_id"`
	UserID     uuid.NullUUID         `json:"user_id"`
	Action     string                `json:"action"`
	EntityType string                `json:"entity_type"`
	EntityID   uuid.NullUUID         `json:"entity_id"`
	Payload    pqtype.NullRawMessage `json:"payload"`
	CreatedAt  time.Time             `json:"created_at"`
}

type Business struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Slug         string         `json:"slug"`
	OwnerID      uuid.UUID      `json:"owner_id"`
	CategoryID   uuid.NullUUID  `json:"category_id"`
	ContactPhone sql.NullString `json:"contact_phone"`
	ContactEmail sql.NullString `json:"contact_email"`
	LogoUrl      sql.NullString `json:"logo_url"`
	Plan         string         `json:"plan"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}

type BusinessCategory struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	NameAr string    `json:"name_ar"`
	Slug   string    `json:"slug"`
}

type CustomerChannel struct {
	ID                uuid.UUID `json:"id"`
	CustomerProfileID uuid.UUID `json:"customer_profile_id"`
	ChannelType       string    `json:"channel_type"`
	ChannelExternalID string    `json:"channel_external_id"`
	CreatedAt         time.Time `json:"created_at"`
}

type CustomerProfile struct {
	ID              uuid.UUID      `json:"id"`
	BusinessID      uuid.UUID      `json:"business_id"`
	UnifiedName     sql.NullString `json:"unified_name"`
	CustomerTier    string         `json:"customer_tier"`
	SemanticSummary sql.NullString `json:"semantic_summary"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type InteractionLog struct {
	ID          uuid.UUID `json:"id"`
	BusinessID  uuid.UUID `json:"business_id"`
	CustomerID  uuid.UUID `json:"customer_id"`
	Channel     string    `json:"channel"`
	InboundMsg  string    `json:"inbound_msg"`
	OutboundMsg string    `json:"outbound_msg"`
	TokensUsed  int32     `json:"tokens_used"`
	LatencyMs   int32     `json:"latency_ms"`
	CreatedAt   time.Time `json:"created_at"`
}

type InteractionTrace struct {
	ID                uuid.UUID       `json:"id"`
	InteractionLogID  uuid.UUID       `json:"interaction_log_id"`
	RetrievedContexts json.RawMessage `json:"retrieved_contexts"`
	SystemPrompt      string          `json:"system_prompt"`
	RawAgentThoughts  string          `json:"raw_agent_thoughts"`
	ToolsCalled       json.RawMessage `json:"tools_called"`
	CreatedAt         time.Time       `json:"created_at"`
}

type Invitation struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	Email      string    `json:"email"`
	Role       string    `json:"role"`
	Token      string    `json:"token"`
	InvitedBy  uuid.UUID `json:"invited_by"`
	Status     string    `json:"status"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type JoinRequest struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	BusinessID uuid.UUID      `json:"business_id"`
	Message    sql.NullString `json:"message"`
	Role       string         `json:"role"`
	Status     string         `json:"status"`
	ReviewedBy uuid.NullUUID  `json:"reviewed_by"`
	ReviewedAt sql.NullTime   `json:"reviewed_at"`
	CreatedAt  time.Time      `json:"created_at"`
}

type KnowledgeNode struct {
	ID         uuid.UUID   `json:"id"`
	BusinessID uuid.UUID   `json:"business_id"`
	SourceName string      `json:"source_name"`
	Content    string      `json:"content"`
	Embedding  interface{} `json:"embedding"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Order struct {
	ID         uuid.UUID       `json:"id"`
	BusinessID uuid.UUID       `json:"business_id"`
	CustomerID uuid.UUID       `json:"customer_id"`
	TotalPrice decimal.Decimal `json:"total_price"`
	Status     string          `json:"status"`
	Source     string          `json:"source"`
	Notes      sql.NullString  `json:"notes"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type OrderItem struct {
	ID        uuid.UUID       `json:"id"`
	OrderID   uuid.UUID       `json:"order_id"`
	ProductID uuid.UUID       `json:"product_id"`
	Sku       string          `json:"sku"`
	Name      string          `json:"name"`
	Quantity  int32           `json:"quantity"`
	UnitPrice decimal.Decimal `json:"unit_price"`
}

type Product struct {
	ID          uuid.UUID       `json:"id"`
	BusinessID  uuid.UUID       `json:"business_id"`
	Sku         string          `json:"sku"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Price       decimal.Decimal `json:"price"`
	StockQty    int32           `json:"stock_qty"`
	IsActive    bool            `json:"is_active"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	DeletedAt   sql.NullTime    `json:"deleted_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Phone        sql.NullString `json:"phone"`
	PasswordHash string         `json:"password_hash"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}

type UserBusinessMembership struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	BusinessID uuid.UUID     `json:"business_id"`
	Role       string        `json:"role"`
	Status     string        `json:"status"`
	InvitedBy  uuid.NullUUID `json:"invited_by"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}
