// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  business_id, customer_id, total_price, status, source, notes
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, business_id, customer_id, total_price, status, source, notes, created_at, updated_at
`

type CreateOrderParams struct {
	BusinessID uuid.UUID       `json:"business_id"`
	CustomerID uuid.UUID       `json:"customer_id"`
	TotalPrice decimal.Decimal `json:"total_price"`
	Status     string          `json:"status"`
	Source     string          `json:"source"`
	Notes      sql.NullString  `json:"notes"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.BusinessID,
		arg.CustomerID,
		arg.TotalPrice,
		arg.Status,
		arg.Source,
		arg.Notes,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.TotalPrice,
		&i.Status,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
  order_id, product_id, sku, name, quantity, unit_price
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, order_id, product_id, sku, name, quantity, unit_price
`

type CreateOrderItemParams struct {
	OrderID   uuid.UUID       `json:"order_id"`
	ProductID uuid.UUID       `json:"product_id"`
	Sku       string          `json:"sku"`
	Name      string          `json:"name"`
	Quantity  int32           `json:"quantity"`
	UnitPrice decimal.Decimal `json:"unit_price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Quantity,
		&i.UnitPrice,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, business_id, customer_id, total_price, status, source, notes, created_at, updated_at FROM orders
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.TotalPrice,
		&i.Status,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, sku, name, quantity, unit_price FROM order_items
WHERE order_id = $1
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.Quantity,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, business_id, customer_id, total_price, status, source, notes, created_at, updated_at FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByCustomer(ctx context.Context, customerID uuid.UUID) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.CustomerID,
			&i.TotalPrice,
			&i.Status,
			&i.Source,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2
WHERE id = $1
RETURNING id, business_id, customer_id, total_price, status, source, notes, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.CustomerID,
		&i.TotalPrice,
		&i.Status,
		&i.Source,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
