// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  business_id, sku, name, description, price, stock_qty
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, business_id, sku, name, description, price, stock_qty, is_active, created_at, updated_at, deleted_at
`

type CreateProductParams struct {
	BusinessID  uuid.UUID       `json:"business_id"`
	Sku         string          `json:"sku"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Price       decimal.Decimal `json:"price"`
	StockQty    int32           `json:"stock_qty"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.BusinessID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.StockQty,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQty,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decrementStock = `-- name: DecrementStock :one
UPDATE products
SET stock_qty = stock_qty - $1
WHERE id = $2
  AND stock_qty >= $1
  AND deleted_at IS NULL
RETURNING id, business_id, sku, name, description, price, stock_qty, is_active, created_at, updated_at, deleted_at
`

type DecrementStockParams struct {
	Quantity int32     `json:"quantity"`
	ID       uuid.UUID `json:"id"`
}

// Atomically decrements stock. Returns error (no rows) if insufficient stock.
func (q *Queries) DecrementStock(ctx context.Context, arg DecrementStockParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, decrementStock, arg.Quantity, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQty,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, business_id, sku, name, description, price, stock_qty, is_active, created_at, updated_at, deleted_at FROM products
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQty,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, business_id, sku, name, description, price, stock_qty, is_active, created_at, updated_at, deleted_at FROM products
WHERE business_id = $1
  AND sku = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetProductBySKUParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Sku        string    `json:"sku"`
}

func (q *Queries) GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductBySKU, arg.BusinessID, arg.Sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQty,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, business_id, sku, name, description, price, stock_qty, is_active, created_at, updated_at, deleted_at FROM products
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.StockQty,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteProduct, id)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
  name        = COALESCE($1,        name),
  description = COALESCE($2, description),
  price       = COALESCE($3,       price),
  is_active   = COALESCE($4,   is_active)
WHERE id = $5
  AND deleted_at IS NULL
RETURNING id, business_id, sku, name, description, price, stock_qty, is_active, created_at, updated_at, deleted_at
`

type UpdateProductParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Price       sql.NullString `json:"price"`
	IsActive    sql.NullBool   `json:"is_active"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.IsActive,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.StockQty,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
