// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, token string) (Invitation, error)
	// queries/businesses.sql
	CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error)
	CreateCustomerProfile(ctx context.Context, arg CreateCustomerProfileParams) (CustomerProfile, error)
	CreateInteractionLog(ctx context.Context, arg CreateInteractionLogParams) (InteractionLog, error)
	CreateInteractionTrace(ctx context.Context, arg CreateInteractionTraceParams) (InteractionTrace, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (JoinRequest, error)
	// queries/memberships.sql
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (UserBusinessMembership, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Atomically decrements stock. Returns error (no rows) if insufficient stock.
	DecrementStock(ctx context.Context, arg DecrementStockParams) (Product, error)
	ExpireInvitation(ctx context.Context, id uuid.UUID) error
	GetBusinessByID(ctx context.Context, id uuid.UUID) (Business, error)
	GetBusinessBySlug(ctx context.Context, slug string) (Business, error)
	// Primary Synapse lookup: find a customer from their external channel ID.
	GetCustomerByChannel(ctx context.Context, arg GetCustomerByChannelParams) (CustomerProfile, error)
	GetCustomerProfileByID(ctx context.Context, id uuid.UUID) (CustomerProfile, error)
	// Fetches a single interaction log and its associated trace for Compass.
	GetInteractionWithTrace(ctx context.Context, id uuid.UUID) (GetInteractionWithTraceRow, error)
	GetInvitationByToken(ctx context.Context, token string) (Invitation, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (UserBusinessMembership, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetPendingJoinRequest(ctx context.Context, arg GetPendingJoinRequestParams) (JoinRequest, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (Product, error)
	// queries/users.sql
	// sqlc generates type-safe Go from these queries.
	// Run: sqlc generate (from backend/)
	//
	// Convention:
	//   :one   → returns a single row (error if not found)
	//   :many  → returns a slice
	//   :exec  → returns only error
	//   :execrows → returns rows affected + error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListBusinessCategories(ctx context.Context) ([]BusinessCategory, error)
	ListBusinessMembers(ctx context.Context, businessID uuid.UUID) ([]ListBusinessMembersRow, error)
	// Paginated list for Compass dashboard.
	ListInteractionLogs(ctx context.Context, arg ListInteractionLogsParams) ([]InteractionLog, error)
	ListInteractionLogsByCustomer(ctx context.Context, customerID uuid.UUID) ([]InteractionLog, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrdersByCustomer(ctx context.Context, customerID uuid.UUID) ([]Order, error)
	ListPendingJoinRequests(ctx context.Context, businessID uuid.UUID) ([]ListPendingJoinRequestsRow, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListUserBusinesses(ctx context.Context, userID uuid.UUID) ([]ListUserBusinessesRow, error)
	ReviewJoinRequest(ctx context.Context, arg ReviewJoinRequestParams) (JoinRequest, error)
	SoftDeleteProduct(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error)
	UpdateCustomerTier(ctx context.Context, arg UpdateCustomerTierParams) (CustomerProfile, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (UserBusinessMembership, error)
	UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (UserBusinessMembership, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSemanticSummary(ctx context.Context, arg UpdateSemanticSummaryParams) (CustomerProfile, error)
	// Resolves or creates the channel mapping, returning the customer profile.
	// Used by Synapse on every inbound message to identify the customer.
	UpsertCustomerChannel(ctx context.Context, arg UpsertCustomerChannelParams) (CustomerChannel, error)
}

var _ Querier = (*Queries)(nil)
