// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM system_secrets
WHERE business_id = $1
  AND key_name = $2
`

type DeleteSecretParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	KeyName    string    `json:"key_name"`
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, arg.BusinessID, arg.KeyName)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT id, business_id, key_name, encrypted_val, created_at, updated_at FROM system_secrets
WHERE business_id = $1
  AND key_name = $2
`

type GetSecretParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	KeyName    string    `json:"key_name"`
}

// Retrieves a single encrypted secret by business + key name.
func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (SystemSecret, error) {
	row := q.db.QueryRowContext(ctx, getSecret, arg.BusinessID, arg.KeyName)
	var i SystemSecret
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.KeyName,
		&i.EncryptedVal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecretKeys = `-- name: ListSecretKeys :many
SELECT id, business_id, key_name, created_at, updated_at
FROM system_secrets
WHERE business_id = $1
ORDER BY key_name ASC
`

type ListSecretKeysRow struct {
	ID         uuid.UUID `json:"id"`
	BusinessID uuid.UUID `json:"business_id"`
	KeyName    string    `json:"key_name"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// Lists all key names (NOT values) for a business — for the admin UI.
func (q *Queries) ListSecretKeys(ctx context.Context, businessID uuid.UUID) ([]ListSecretKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecretKeys, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretKeysRow{}
	for rows.Next() {
		var i ListSecretKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.KeyName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSecret = `-- name: UpsertSecret :one

INSERT INTO system_secrets (business_id, key_name, encrypted_val)
VALUES ($1, $2, $3)
ON CONFLICT (business_id, key_name)
DO UPDATE SET encrypted_val = EXCLUDED.encrypted_val
RETURNING id, business_id, key_name, encrypted_val, created_at, updated_at
`

type UpsertSecretParams struct {
	BusinessID   uuid.UUID `json:"business_id"`
	KeyName      string    `json:"key_name"`
	EncryptedVal string    `json:"encrypted_val"`
}

// queries/secrets.sql
// Inserts or updates a secret for a business.
// The value must be encrypted BEFORE calling this query.
func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) (SystemSecret, error) {
	row := q.db.QueryRowContext(ctx, upsertSecret, arg.BusinessID, arg.KeyName, arg.EncryptedVal)
	var i SystemSecret
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.KeyName,
		&i.EncryptedVal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
