// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traces.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const listTraces = `-- name: ListTraces :many
SELECT 
  it.id AS trace_id,
  it.interaction_log_id,
  it.retrieved_contexts,
  it.system_prompt,
  it.raw_agent_thoughts,
  it.tools_called,
  it.created_at AS trace_created_at,
  il.id AS log_id,
  il.business_id,
  il.customer_id,
  il.channel,
  il.inbound_msg,
  il.outbound_msg,
  il.tokens_used,
  il.latency_ms,
  il.created_at AS log_created_at
FROM interaction_traces it
JOIN interaction_logs il ON it.interaction_log_id = il.id
WHERE il.business_id = $1
ORDER BY il.created_at DESC
LIMIT $3 OFFSET $2
`

type ListTracesParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Off        int32     `json:"off"`
	Lim        int32     `json:"lim"`
}

type ListTracesRow struct {
	TraceID           uuid.UUID       `json:"trace_id"`
	InteractionLogID  uuid.UUID       `json:"interaction_log_id"`
	RetrievedContexts json.RawMessage `json:"retrieved_contexts"`
	SystemPrompt      string          `json:"system_prompt"`
	RawAgentThoughts  string          `json:"raw_agent_thoughts"`
	ToolsCalled       json.RawMessage `json:"tools_called"`
	TraceCreatedAt    time.Time       `json:"trace_created_at"`
	LogID             uuid.UUID       `json:"log_id"`
	BusinessID        uuid.UUID       `json:"business_id"`
	CustomerID        uuid.UUID       `json:"customer_id"`
	Channel           string          `json:"channel"`
	InboundMsg        string          `json:"inbound_msg"`
	OutboundMsg       string          `json:"outbound_msg"`
	TokensUsed        int32           `json:"tokens_used"`
	LatencyMs         int32           `json:"latency_ms"`
	LogCreatedAt      time.Time       `json:"log_created_at"`
}

func (q *Queries) ListTraces(ctx context.Context, arg ListTracesParams) ([]ListTracesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTraces, arg.BusinessID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTracesRow{}
	for rows.Next() {
		var i ListTracesRow
		if err := rows.Scan(
			&i.TraceID,
			&i.InteractionLogID,
			&i.RetrievedContexts,
			&i.SystemPrompt,
			&i.RawAgentThoughts,
			&i.ToolsCalled,
			&i.TraceCreatedAt,
			&i.LogID,
			&i.BusinessID,
			&i.CustomerID,
			&i.Channel,
			&i.InboundMsg,
			&i.OutboundMsg,
			&i.TokensUsed,
			&i.LatencyMs,
			&i.LogCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
